#!/bin/bash
#
# print cleaned and uniq'd file list of zip archive root
#
# useful for removeing all files/folders of example.zip
# $ list-archive example.zip | xargs rm -r

listzip () {
  unzip -l "$@" |\
    tail -n +4 |\
    head -n -2 |\
    awk '{ print $4; }'
}

listrar () {
  unrar v "$@" |\
    tail -n +9 |\
    head -n -3 |\
    grep -v '%'
}

prettify () {
  echo "$@" |\
    sed -r 's/\/.*//' |\
    sort | uniq
}


case ${1##*.} in
  "zip")
    c=$(listzip "$1")
    ;;
  "rar")
    c=$(listrar "$1")
    ;;
  "tgz"|"txz"|"gz"|"xz")
    c=$(tar -tf "$1")
    ;;
  *)
    echo ERROR: incompatible file type
    exit 1
    ;;
esac

prettify "$c"
